services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@1"
    platform: "linux/amd64" # needed only if running on an ARM chips (which I do)
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql # setting a name to the volume in order to persist the data even after the container is stopped
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data # setting a name to the volume in order to persist the data even after the container is stopped

# Specifying the DB we are using
volumes:
  redis-data:
  sql-data:
